//
//  Populate database with sample data
//
const { Conversion } = require("../models");

const conversionData = [
  {
    item: "703250",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "617950",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "614910",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "616265",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "501080",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "608175",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "9",
    user: "admin",
  },
  {
    item: "608515",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "9",
    user: "admin",
  },
  {
    item: "400686",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "400684",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "608966",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "608844",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "608845",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "606385",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "605054",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "604716",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "603725",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "16",
    user: "admin",
  },
  {
    item: "603525",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "611970",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "606365",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "603935",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "606197",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "616266",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "613280",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "613281",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "613282",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "605075",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "605076",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "611632",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "609875",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "402660",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "609940",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "609930",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "611350",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611630",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "610680",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "600190",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "160",
    user: "admin",
  },
  {
    item: "600230",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "160",
    user: "admin",
  },
  {
    item: "610990",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "603271",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "610986",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "601680",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "50",
    user: "admin",
  },
  {
    item: "601614",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "601615",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "610985",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611040",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "603840",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "603847",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "611050",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "604596",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "603810",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "611070",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "610980",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611010",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611430",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "605610",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "605590",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "601600",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "601610",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "604320",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "603240",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "604650",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "605780",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "602210",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "601980",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "604392",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "602080",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "604390",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "604400",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "609620",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "609630",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "609640",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "609660",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "609590",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "608386",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "608556",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "608555",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "608384",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "607550",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "607480",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "607470",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "607460",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "607450",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "607530",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "607520",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "607510",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "607500",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "607570",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "608431",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "9",
    user: "admin",
  },
  {
    item: "608432",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "9",
    user: "admin",
  },
  {
    item: "607610",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "20",
    user: "admin",
  },
  {
    item: "608170",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "9",
    user: "admin",
  },
  {
    item: "608140",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "9",
    user: "admin",
  },
  {
    item: "608093",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "608094",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "608390",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "608500",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "608564",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "608640",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "608660",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "607811",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "608560",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "608530",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "9",
    user: "admin",
  },
  {
    item: "608520",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "9",
    user: "admin",
  },
  {
    item: "608670",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "608610",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "607801",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "608150",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "9",
    user: "admin",
  },
  {
    item: "608160",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "9",
    user: "admin",
  },
  {
    item: "608100",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "9",
    user: "admin",
  },
  {
    item: "402310",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "402311",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "401025",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "605330",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "605320",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "601420",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "48",
    user: "admin",
  },
  {
    item: "601430",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "48",
    user: "admin",
  },
  {
    item: "601400",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "48",
    user: "admin",
  },
  {
    item: "602400",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "601260",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "48",
    user: "admin",
  },
  {
    item: "601240",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "100",
    user: "admin",
  },
  {
    item: "601320",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "48",
    user: "admin",
  },
  {
    item: "611560",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "616630",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "616752",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "616730",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "603060",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "16",
    user: "admin",
  },
  {
    item: "614681",
    uomFrom: "6CT",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    item: "614683",
    uomFrom: "6CT",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    item: "614682",
    uomFrom: "6CT",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    item: "603171",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "16",
    user: "admin",
  },
  {
    item: "603120",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "16",
    user: "admin",
  },
  {
    item: "300900",
    uomFrom: "BWL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "300890",
    uomFrom: "BWL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "300880",
    uomFrom: "BWL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "616740",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "616770",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "616760",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "616430",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "616420",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "616540",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "616550",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "606470",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "606460",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "616663",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "616583",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "603126",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "603129",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "15",
    user: "admin",
  },
  {
    item: "603128",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "15",
    user: "admin",
  },
  {
    item: "603110",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "603170",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "616660",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "603140",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "16",
    user: "admin",
  },
  {
    item: "603150",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "16",
    user: "admin",
  },
  {
    item: "616637",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "616667",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "606463",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "616450",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "616580",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "616761",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "616541",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "616636",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "616635",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "616638",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "616547",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "616634",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "616330",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "616750",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "402260",
    uomFrom: "BTL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "402270",
    uomFrom: "BTL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "618290",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "16",
    user: "admin",
  },
  {
    item: "618293",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "16",
    user: "admin",
  },
  {
    item: "618411",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "618370",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "618310",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "618320",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "618375",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "618373",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "618372",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "618270",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "618280",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "618250",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "618288",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "617992",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "617991",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "617993",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "400765",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "617996",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "400773",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "400750",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "400740",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "618324",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "618482",
    uomFrom: "STK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "618483",
    uomFrom: "BG",
    uomTo: "BG",
    factor: "1",
    user: "admin",
  },
  {
    item: "618486",
    uomFrom: "STK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "618485",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "618484",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "400760",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "618489",
    uomFrom: "STK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "618488",
    uomFrom: "STK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "617997",
    uomFrom: "BG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "617995",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "617994",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "618334",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "618336",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "618002",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "400770",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "400777",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "400779",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "400775",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "72",
    user: "admin",
  },
  {
    item: "400778",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "400776",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "614736",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    item: "614735",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    item: "503010",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "609800",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "20",
    user: "admin",
  },
  {
    item: "609810",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "20",
    user: "admin",
  },
  {
    item: "609770",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "20",
    user: "admin",
  },
  {
    item: "609830",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "20",
    user: "admin",
  },
  {
    item: "611310",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611320",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "610540",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "610550",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "610570",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "610530",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "610560",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611241",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "612950",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "612970",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "612910",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "613010",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "612990",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "612943",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "612930",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "613000",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "612980",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "612976",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "612977",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "612920",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "620130",
    uomFrom: "BWL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "300459",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "300457",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "300455",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "300456",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "300458",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611244",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "608753",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "607701",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "609530",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "607720",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "609790",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "20",
    user: "admin",
  },
  {
    item: "609840",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "20",
    user: "admin",
  },
  {
    item: "608782",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "608781",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "606381",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "608925",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "605053",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "608880",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "608790",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "608840",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "608720",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "608890",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "608785",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "608789",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "609432",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "9",
    user: "admin",
  },
  {
    item: "609433",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "9",
    user: "admin",
  },
  {
    item: "605225",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "609060",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "608680",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "608740",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "608700",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "608710",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "608730",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "607930",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "40",
    user: "admin",
  },
  {
    item: "607910",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "40",
    user: "admin",
  },
  {
    item: "607920",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "40",
    user: "admin",
  },
  {
    item: "607900",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "40",
    user: "admin",
  },
  {
    item: "607940",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "40",
    user: "admin",
  },
  {
    item: "608793",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "608756",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "605172",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "608786",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "609140",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "609050",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "609071",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "609000",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "609070",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "608990",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "607026",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "607704",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "608939",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "608797",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "611322",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "15",
    user: "admin",
  },
  {
    item: "608788",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "609410",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "609420",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "608970",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "608980",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "608964",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "608920",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "608930",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "608940",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "611280",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611787",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611316",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "606870",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "606840",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "606880",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "606910",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "607020",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "501770",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "501800",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "501730",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "501740",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "501750",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "501790",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "614280",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "614290",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "614270",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "614940",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "614950",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "615240",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "614945",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "614271",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "614951",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "302771",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "302750",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "618750",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "618660",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "618710",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "618740",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "618730",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "618674",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "618661",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "618755",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "618659",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "618658",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "618657",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "618670",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "15",
    user: "admin",
  },
  {
    item: "618680",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "613185",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "613190",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "613953",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "613170",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "613200",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "613180",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "613201",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "617085",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "617091",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "617092",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "618605",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "100",
    user: "admin",
  },
  {
    item: "618615",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "618617",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "602630",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "602520",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "604900",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "611120",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "602550",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "604670",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "600620",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "145",
    user: "admin",
  },
  {
    item: "611121",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "604450",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "602320",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "611891",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "604490",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "606300",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "602310",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "602330",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "602350",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "602280",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "602340",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "606260",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "605640",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "605630",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "602300",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "600580",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "165",
    user: "admin",
  },
  {
    item: "600560",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "165",
    user: "admin",
  },
  {
    item: "600600",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "165",
    user: "admin",
  },
  {
    item: "600520",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "165",
    user: "admin",
  },
  {
    item: "600640",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "165",
    user: "admin",
  },
  {
    item: "600530",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "165",
    user: "admin",
  },
  {
    item: "400650",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "400610",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "400622",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "400670",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "616850",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "613630",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "613950",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "613921",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "613960",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "613801",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "613825",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "613826",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "613861",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "613860",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "613970",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "613620",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "613810",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "613820",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "613850",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "613800",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "613880",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "613631",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "603051",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "614580",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "614523",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "614522",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "614970",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "614730",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "614770",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "614766",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "614760",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "614750",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "614765",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "614520",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "614763",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "600160",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "120",
    user: "admin",
  },
  {
    item: "600760",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "100",
    user: "admin",
  },
  {
    item: "606320",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "606310",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "605720",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "601070",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "175",
    user: "admin",
  },
  {
    item: "618036",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "618037",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "603590",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "611550",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "610860",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "605850",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "603275",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "603455",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "603600",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "20",
    user: "admin",
  },
  {
    item: "603610",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "602950",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "605771",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "605930",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "605890",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "605900",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "610830",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "605830",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "605760",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "605860",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "605800",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "605950",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "603445",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "603451",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "603270",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "603330",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "603421",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "603280",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "603285",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "603370",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "603510",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "603390",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "603450",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "603290",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "603690",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "603620",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "605838",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "605770",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "603660",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "610910",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "603630",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "605790",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "601040",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "105",
    user: "admin",
  },
  {
    item: "600890",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "120",
    user: "admin",
  },
  {
    item: "603720",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "16",
    user: "admin",
  },
  {
    item: "605772",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "603540",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "603580",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "610850",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "605837",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "16",
    user: "admin",
  },
  {
    item: "603511",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "16",
    user: "admin",
  },
  {
    item: "604715",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "605920",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "605960",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "603520",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "605773",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "605280",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "604590",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "605940",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "15",
    user: "admin",
  },
  {
    item: "600790",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "180",
    user: "admin",
  },
  {
    item: "611590",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611990",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611960",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611950",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611980",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611995",
    uomFrom: "BG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "612010",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "604595",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "607350",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "607370",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "609480",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "609560",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "609540",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "609491",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "609270",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "609290",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "609280",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "609297",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    item: "609298",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "609271",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "609272",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "609275",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "604700",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "604680",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "604720",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "602660",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "609773",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "609774",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "400901",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "4",
    user: "admin",
  },
  {
    item: "400890",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "30",
    user: "admin",
  },
  {
    item: "506570",
    uomFrom: "JUG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "506571",
    uomFrom: "BTL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "617380",
    uomFrom: "PK",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "617370",
    uomFrom: "PK",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "617340",
    uomFrom: "PK",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "617390",
    uomFrom: "CSE",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "617094",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "617095",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "617096",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "503745",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "506501",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "615210",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    item: "614670",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    item: "614720",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "614660",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    item: "614680",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    item: "614650",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    item: "615140",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    item: "606510",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "614713",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "614630",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "615170",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    item: "615190",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    item: "615200",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    item: "615220",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    item: "614712",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "614780",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "16",
    user: "admin",
  },
  {
    item: "614790",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "16",
    user: "admin",
  },
  {
    item: "614800",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "16",
    user: "admin",
  },
  {
    item: "614810",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "16",
    user: "admin",
  },
  {
    item: "615160",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    item: "606530",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "20",
    user: "admin",
  },
  {
    item: "606511",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "20",
    user: "admin",
  },
  {
    item: "618870",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "618900",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "618910",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "618880",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "618860",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "201461",
    uomFrom: "CAN",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "201500",
    uomFrom: "CSE",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "604080",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "604060",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "605180",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "605190",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "605050",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "605080",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "605070",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "604020",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "48",
    user: "admin",
  },
  {
    item: "603960",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "48",
    user: "admin",
  },
  {
    item: "603950",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "605060",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "611700",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611660",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611670",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611680",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "603945",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "606240",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "606230",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "606190",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "604030",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "606380",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "611781",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611720",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611730",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611750",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611740",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "606390",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "605171",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "606250",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "611490",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611500",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611434",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611433",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "606360",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "606400",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "604218",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "90",
    user: "admin",
  },
  {
    item: "605220",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "606430",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "604250",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "606420",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "604240",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "606196",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "604076",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "606245",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "603957",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "606435",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "604065",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "604077",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "603944",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "603946",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "603948",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "604070",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "604130",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "604200",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "48",
    user: "admin",
  },
  {
    item: "606232",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "603953",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "603954",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "606231",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "604211",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "602690",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "604660",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "604661",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "609341",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "600120",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "48",
    user: "admin",
  },
  {
    item: "602440",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "602770",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "709930",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "1000",
    user: "admin",
  },
  {
    item: "506531",
    uomFrom: "BTL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "502020",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "502040",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "501990",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "502010",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "502240",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "502030",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "604950",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "605261",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "604960",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "605000",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "616300",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "616260",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "616270",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "616290",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "616280",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "602852",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "616271",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "602820",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "602860",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "602840",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "600550",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "150",
    user: "admin",
  },
  {
    item: "600410",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "150",
    user: "admin",
  },
  {
    item: "610160",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "610180",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "602110",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "602090",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "601140",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "602120",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "602113",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "602140",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "602100",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "602111",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "602116",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "602119",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "610240",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "610290",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "610270",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "610250",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "610310",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "613250",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "613260",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "613272",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "613271",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "613270",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "613240",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "708410",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "708561",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "708600",
    uomFrom: "CS",
    uomTo: "CS",
    factor: "1",
    user: "admin",
  },
  {
    item: "708580",
    uomFrom: "CS",
    uomTo: "BX",
    factor: "1",
    user: "admin",
  },
  {
    item: "708470",
    uomFrom: "CS1",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "600800",
    uomFrom: "TUB",
    uomTo: "EA",
    factor: "300",
    user: "admin",
  },
  {
    item: "400871",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "25",
    user: "admin",
  },
  {
    item: "617850",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "20",
    user: "admin",
  },
  {
    item: "400870",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "506371",
    uomFrom: "PAK",
    uomTo: "RL",
    factor: "1",
    user: "admin",
  },
  {
    item: "400430",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "400431",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "400432",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "615060",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "615050",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "615080",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "615090",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "615040",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "615030",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "614880",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "614830",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "614450",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "615130",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "614900",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "614410",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "614320",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "614350",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "614380",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "614924",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "15",
    user: "admin",
  },
  {
    item: "614401",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "614330",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "614440",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "614430",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "617780",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "617790",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "617671",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "617670",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "617730",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "617720",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "617710",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "617640",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "617650",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "617680",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "617700",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "617630",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "617600",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "617610",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "617690",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "617750",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "617590",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "201721",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "201561",
    uomFrom: "BTL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "301950",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "200600",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "300186",
    uomFrom: "BWL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "200840",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "200850",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "200860",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "200990",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "400710",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "400660",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "400630",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "400680",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "400600",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "400690",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "400640",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "400880",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "4",
    user: "admin",
  },
  {
    item: "601190",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "607030",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "607040",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "600430",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "240",
    user: "admin",
  },
  {
    item: "600570",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "240",
    user: "admin",
  },
  {
    item: "601192",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "601193",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "601191",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "601198",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "400688",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "301627",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "301626",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "704900",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "501070",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "611629",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611634",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611633",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "613020",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "600480",
    uomFrom: "JAR",
    uomTo: "EA",
    factor: "290",
    user: "admin",
  },
  {
    item: "600490",
    uomFrom: "TUB",
    uomTo: "EA",
    factor: "120",
    user: "admin",
  },
  {
    item: "600470",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "120",
    user: "admin",
  },
  {
    item: "600500",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "120",
    user: "admin",
  },
  {
    item: "613025",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "602570",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "503310",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "613070",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "613080",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "602530",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "613030",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "202470",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "202473",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "603740",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "604340",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "604330",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "611190",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611230",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611233",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611360",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611370",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611180",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611351",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611340",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "502927",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "613095",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "602900",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "602870",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "602890",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "613130",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "613090",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "613110",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "502860",
    uomFrom: "BTL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "502970",
    uomFrom: "BTL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "503270",
    uomFrom: "BTL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "502960",
    uomFrom: "BTL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "503280",
    uomFrom: "CAN",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "503320",
    uomFrom: "BTL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "503300",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    item: "502930",
    uomFrom: "CAN",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "503160",
    uomFrom: "BTL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "600810",
    uomFrom: "JAR",
    uomTo: "EA",
    factor: "280",
    user: "admin",
  },
  {
    item: "600361",
    uomFrom: "BG",
    uomTo: "EA",
    factor: "360",
    user: "admin",
  },
  {
    item: "600351",
    uomFrom: "BG",
    uomTo: "EA",
    factor: "360",
    user: "admin",
  },
  {
    item: "600371",
    uomFrom: "BG",
    uomTo: "EA",
    factor: "360",
    user: "admin",
  },
  {
    item: "600341",
    uomFrom: "BG",
    uomTo: "EA",
    factor: "360",
    user: "admin",
  },
  {
    item: "600331",
    uomFrom: "BG",
    uomTo: "EA",
    factor: "360",
    user: "admin",
  },
  {
    item: "600311",
    uomFrom: "BG",
    uomTo: "EA",
    factor: "360",
    user: "admin",
  },
  {
    item: "600381",
    uomFrom: "BG",
    uomTo: "EA",
    factor: "360",
    user: "admin",
  },
  {
    item: "601390",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "48",
    user: "admin",
  },
  {
    item: "602030",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "100",
    user: "admin",
  },
  {
    item: "605510",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "603900",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "600980",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "72",
    user: "admin",
  },
  {
    item: "611456",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "611457",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "611458",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "604290",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "604280",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "602040",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "96",
    user: "admin",
  },
  {
    item: "611410",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611400",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "611450",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "203000",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "619735",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "619732",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    item: "619752",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "619727",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    item: "619800",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "619790",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "619750",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "619770",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "619740",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    item: "619730",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "619711",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    item: "619760",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "619734",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "619733",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "619720",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    item: "619710",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    item: "619751",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "619755",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "604270",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "604271",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "201640",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "302520",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "302530",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "506260",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "618200",
    uomFrom: "BG",
    uomTo: "EA",
    factor: "14",
    user: "admin",
  },
  {
    item: "202698",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "202699",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "202693",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "601160",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "601080",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "601090",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "601091",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "601130",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "601120",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "601060",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "609876",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "609880",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "15",
    user: "admin",
  },
  {
    item: "609870",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "15",
    user: "admin",
  },
  {
    item: "609850",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "15",
    user: "admin",
  },
  {
    item: "609890",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "15",
    user: "admin",
  },
  {
    item: "609881",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "15",
    user: "admin",
  },
  {
    item: "601092",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "602500",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "602504",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "602506",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "602507",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "602511",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "602508",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "602501",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "502910",
    uomFrom: "BTL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "618170",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "618190",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "612328",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "612540",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "612240",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "612210",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "612530",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "612710",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "612250",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "612316",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "612192",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "612332",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "612331",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "612315",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "612370",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "612314",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "612150",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "612330",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "612294",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "612510",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "612270",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "612303",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "612334",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "612306",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "612200",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "612180",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "612308",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "503403",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "503404",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "503408",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "503402",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "503409",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "503406",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "614960",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "614200",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "605520",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "605660",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "604945",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "604930",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "604946",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "604947",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "619110",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "611855",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "190",
    user: "admin",
  },
  {
    item: "606330",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    item: "601010",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "240",
    user: "admin",
  },
  {
    item: "619135",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "60",
    user: "admin",
  },
  {
    item: "202630",
    uomFrom: "CS",
    uomTo: "PK",
    factor: "24",
    user: "admin",
  },
  {
    item: "202640",
    uomFrom: "CS",
    uomTo: "PK",
    factor: "24",
    user: "admin",
  },
  {
    item: "616480",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "616490",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "616470",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "501460",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "501470",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "501430",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "501450",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "501420",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    item: "402140",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "503350",
    uomFrom: "SQG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "617870",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "617910",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "32",
    user: "admin",
  },
  {
    item: "601360",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "602011",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "48",
    user: "admin",
  },
  {
    item: "611161",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "604511",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "602760",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "605360",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "611890",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "605140",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "611162",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "605430",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "605460",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "604510",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "605130",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "604500",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "604570",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "604540",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    item: "604970",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "611150",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "605448",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "605131",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "604560",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "602750",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "611140",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "605449",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "605447",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "611160",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "504980",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "707430",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "707550",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "500",
    user: "admin",
  },
  {
    item: "707630",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "707470",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "503020",
    uomFrom: "SLV",
    uomTo: "SLV",
    factor: "12",
    user: "admin",
  },
  {
    item: "201015",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    item: "604990",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "601950",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "48",
    user: "admin",
  },
  {
    item: "401015",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "604948",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "601753",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "601752",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "601757",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "601751",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "601756",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "601754",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "600720",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "192",
    user: "admin",
  },
  {
    item: "604620",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    item: "302531",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    item: "606570",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "606632",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "15",
    user: "admin",
  },
  {
    item: "606600",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "15",
    user: "admin",
  },
  {
    item: "606628",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    item: "606630",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "15",
    user: "admin",
  },
  {
    item: "606625",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "15",
    user: "admin",
  },
];

const seedConversion = async () => {
  await Conversion.deleteMany({});
  await Conversion.insertMany(conversionData);
};

module.exports = seedConversion;
