//
//  Populate database with sample data
//
const { Conversion } = require("../models");

const conversionData = [
  {
    sku: "703250",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "617950",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "614910",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "616265",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "501080",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "608175",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "9",
    user: "admin",
  },
  {
    sku: "608515",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "9",
    user: "admin",
  },
  {
    sku: "400686",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "400684",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "608966",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "608844",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "608845",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "606385",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "605054",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "604716",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "603725",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "16",
    user: "admin",
  },
  {
    sku: "603525",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "611970",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "606365",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "603935",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "606197",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "616266",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "613280",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "613281",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "613282",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "605075",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "605076",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "611632",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "609875",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "402660",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "609940",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "609930",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "611350",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611630",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "610680",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "600190",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "160",
    user: "admin",
  },
  {
    sku: "600230",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "160",
    user: "admin",
  },
  {
    sku: "610990",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "603271",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "610986",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "601680",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "50",
    user: "admin",
  },
  {
    sku: "601614",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "601615",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "610985",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611040",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "603840",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "603847",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "611050",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "604596",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "603810",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "611070",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "610980",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611010",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611430",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "605610",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "605590",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "601600",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "601610",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "604320",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "603240",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "604650",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "605780",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "602210",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "601980",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "604392",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "602080",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "604390",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "604400",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "609620",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "609630",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "609640",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "609660",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "609590",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "608386",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "608556",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "608555",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "608384",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "607550",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "607480",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "607470",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "607460",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "607450",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "607530",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "607520",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "607510",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "607500",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "607570",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "608431",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "9",
    user: "admin",
  },
  {
    sku: "608432",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "9",
    user: "admin",
  },
  {
    sku: "607610",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "20",
    user: "admin",
  },
  {
    sku: "608170",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "9",
    user: "admin",
  },
  {
    sku: "608140",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "9",
    user: "admin",
  },
  {
    sku: "608093",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "608094",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "608390",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "608500",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "608564",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "608640",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "608660",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "607811",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "608560",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "608530",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "9",
    user: "admin",
  },
  {
    sku: "608520",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "9",
    user: "admin",
  },
  {
    sku: "608670",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "608610",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "607801",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "608150",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "9",
    user: "admin",
  },
  {
    sku: "608160",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "9",
    user: "admin",
  },
  {
    sku: "608100",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "9",
    user: "admin",
  },
  {
    sku: "402310",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "402311",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "401025",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "605330",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "605320",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "601420",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "48",
    user: "admin",
  },
  {
    sku: "601430",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "48",
    user: "admin",
  },
  {
    sku: "601400",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "48",
    user: "admin",
  },
  {
    sku: "602400",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "601260",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "48",
    user: "admin",
  },
  {
    sku: "601240",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "100",
    user: "admin",
  },
  {
    sku: "601320",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "48",
    user: "admin",
  },
  {
    sku: "611560",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "616630",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "616752",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "616730",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "603060",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "16",
    user: "admin",
  },
  {
    sku: "614681",
    uomFrom: "6CT",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    sku: "614683",
    uomFrom: "6CT",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    sku: "614682",
    uomFrom: "6CT",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    sku: "603171",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "16",
    user: "admin",
  },
  {
    sku: "603120",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "16",
    user: "admin",
  },
  {
    sku: "300900",
    uomFrom: "BWL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "300890",
    uomFrom: "BWL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "300880",
    uomFrom: "BWL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "616740",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "616770",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "616760",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "616430",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "616420",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "616540",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "616550",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "606470",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "606460",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "616663",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "616583",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "603126",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "603129",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "15",
    user: "admin",
  },
  {
    sku: "603128",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "15",
    user: "admin",
  },
  {
    sku: "603110",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "603170",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "616660",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "603140",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "16",
    user: "admin",
  },
  {
    sku: "603150",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "16",
    user: "admin",
  },
  {
    sku: "616637",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "616667",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "606463",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "616450",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "616580",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "616761",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "616541",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "616636",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "616635",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "616638",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "616547",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "616634",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "616330",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "616750",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "402260",
    uomFrom: "BTL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "402270",
    uomFrom: "BTL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "618290",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "16",
    user: "admin",
  },
  {
    sku: "618293",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "16",
    user: "admin",
  },
  {
    sku: "618411",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "618370",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "618310",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "618320",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "618375",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "618373",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "618372",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "618270",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "618280",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "618250",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "618288",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "617992",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "617991",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "617993",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "400765",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "617996",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "400773",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "400750",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "400740",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "618324",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "618482",
    uomFrom: "STK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "618483",
    uomFrom: "BG",
    uomTo: "BG",
    factor: "1",
    user: "admin",
  },
  {
    sku: "618486",
    uomFrom: "STK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "618485",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "618484",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "400760",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "618489",
    uomFrom: "STK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "618488",
    uomFrom: "STK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "617997",
    uomFrom: "BG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "617995",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "617994",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "618334",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "618336",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "618002",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "400770",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "400777",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "400779",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "400775",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "72",
    user: "admin",
  },
  {
    sku: "400778",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "400776",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "614736",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    sku: "614735",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    sku: "503010",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "609800",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "20",
    user: "admin",
  },
  {
    sku: "609810",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "20",
    user: "admin",
  },
  {
    sku: "609770",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "20",
    user: "admin",
  },
  {
    sku: "609830",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "20",
    user: "admin",
  },
  {
    sku: "611310",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611320",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "610540",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "610550",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "610570",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "610530",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "610560",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611241",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "612950",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "612970",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "612910",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "613010",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "612990",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "612943",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "612930",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "613000",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "612980",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "612976",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "612977",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "612920",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "620130",
    uomFrom: "BWL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "300459",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "300457",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "300455",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "300456",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "300458",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611244",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "608753",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "607701",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "609530",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "607720",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "609790",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "20",
    user: "admin",
  },
  {
    sku: "609840",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "20",
    user: "admin",
  },
  {
    sku: "608782",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "608781",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "606381",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "608925",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "605053",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "608880",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "608790",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "608840",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "608720",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "608890",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "608785",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "608789",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "609432",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "9",
    user: "admin",
  },
  {
    sku: "609433",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "9",
    user: "admin",
  },
  {
    sku: "605225",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "609060",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "608680",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "608740",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "608700",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "608710",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "608730",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "607930",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "40",
    user: "admin",
  },
  {
    sku: "607910",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "40",
    user: "admin",
  },
  {
    sku: "607920",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "40",
    user: "admin",
  },
  {
    sku: "607900",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "40",
    user: "admin",
  },
  {
    sku: "607940",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "40",
    user: "admin",
  },
  {
    sku: "608793",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "608756",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "605172",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "608786",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "609140",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "609050",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "609071",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "609000",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "609070",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "608990",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "607026",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "607704",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "608939",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "608797",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "611322",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "15",
    user: "admin",
  },
  {
    sku: "608788",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "609410",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "609420",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "608970",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "608980",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "608964",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "608920",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "608930",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "608940",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "611280",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611787",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611316",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "606870",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "606840",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "606880",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "606910",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "607020",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "501770",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "501800",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "501730",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "501740",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "501750",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "501790",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "614280",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "614290",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "614270",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "614940",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "614950",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "615240",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "614945",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "614271",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "614951",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "302771",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "302750",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "618750",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "618660",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "618710",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "618740",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "618730",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "618674",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "618661",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "618755",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "618659",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "618658",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "618657",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "618670",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "15",
    user: "admin",
  },
  {
    sku: "618680",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "613185",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "613190",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "613953",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "613170",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "613200",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "613180",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "613201",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "617085",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "617091",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "617092",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "618605",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "100",
    user: "admin",
  },
  {
    sku: "618615",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "618617",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "602630",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "602520",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "604900",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "611120",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "602550",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "604670",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "600620",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "145",
    user: "admin",
  },
  {
    sku: "611121",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "604450",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "602320",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "611891",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "604490",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "606300",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "602310",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "602330",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "602350",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "602280",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "602340",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "606260",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "605640",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "605630",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "602300",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "600580",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "165",
    user: "admin",
  },
  {
    sku: "600560",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "165",
    user: "admin",
  },
  {
    sku: "600600",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "165",
    user: "admin",
  },
  {
    sku: "600520",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "165",
    user: "admin",
  },
  {
    sku: "600640",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "165",
    user: "admin",
  },
  {
    sku: "600530",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "165",
    user: "admin",
  },
  {
    sku: "400650",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "400610",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "400622",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "400670",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "616850",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "613630",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "613950",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "613921",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "613960",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "613801",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "613825",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "613826",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "613861",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "613860",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "613970",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "613620",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "613810",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "613820",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "613850",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "613800",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "613880",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "613631",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "603051",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "614580",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "614523",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "614522",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "614970",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "614730",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "614770",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "614766",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "614760",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "614750",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "614765",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "614520",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "614763",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "600160",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "120",
    user: "admin",
  },
  {
    sku: "600760",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "100",
    user: "admin",
  },
  {
    sku: "606320",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "606310",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "605720",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "601070",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "175",
    user: "admin",
  },
  {
    sku: "618036",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "618037",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "603590",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "611550",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "610860",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "605850",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "603275",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "603455",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "603600",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "20",
    user: "admin",
  },
  {
    sku: "603610",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "602950",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "605771",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "605930",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "605890",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "605900",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "610830",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "605830",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "605760",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "605860",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "605800",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "605950",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "603445",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "603451",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "603270",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "603330",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "603421",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "603280",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "603285",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "603370",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "603510",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "603390",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "603450",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "603290",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "603690",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "603620",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "605838",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "605770",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "603660",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "610910",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "603630",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "605790",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "601040",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "105",
    user: "admin",
  },
  {
    sku: "600890",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "120",
    user: "admin",
  },
  {
    sku: "603720",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "16",
    user: "admin",
  },
  {
    sku: "605772",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "603540",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "603580",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "610850",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "605837",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "16",
    user: "admin",
  },
  {
    sku: "603511",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "16",
    user: "admin",
  },
  {
    sku: "604715",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "605920",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "605960",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "603520",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "605773",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "605280",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "604590",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "605940",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "15",
    user: "admin",
  },
  {
    sku: "600790",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "180",
    user: "admin",
  },
  {
    sku: "611590",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611990",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611960",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611950",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611980",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611995",
    uomFrom: "BG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "612010",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "604595",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "607350",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "607370",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "609480",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "609560",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "609540",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "609491",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "609270",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "609290",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "609280",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "609297",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    sku: "609298",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "609271",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "609272",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "609275",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "604700",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "604680",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "604720",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "602660",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "609773",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "609774",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "400901",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "4",
    user: "admin",
  },
  {
    sku: "400890",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "30",
    user: "admin",
  },
  {
    sku: "506570",
    uomFrom: "JUG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "506571",
    uomFrom: "BTL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "617380",
    uomFrom: "PK",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "617370",
    uomFrom: "PK",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "617340",
    uomFrom: "PK",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "617390",
    uomFrom: "CSE",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "617094",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "617095",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "617096",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "503745",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "506501",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "615210",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    sku: "614670",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    sku: "614720",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "614660",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    sku: "614680",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    sku: "614650",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    sku: "615140",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    sku: "606510",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "614713",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "614630",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "615170",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    sku: "615190",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    sku: "615200",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    sku: "615220",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    sku: "614712",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "614780",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "16",
    user: "admin",
  },
  {
    sku: "614790",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "16",
    user: "admin",
  },
  {
    sku: "614800",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "16",
    user: "admin",
  },
  {
    sku: "614810",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "16",
    user: "admin",
  },
  {
    sku: "615160",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    sku: "606530",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "20",
    user: "admin",
  },
  {
    sku: "606511",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "20",
    user: "admin",
  },
  {
    sku: "618870",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "618900",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "618910",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "618880",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "618860",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "201461",
    uomFrom: "CAN",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "201500",
    uomFrom: "CSE",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "604080",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "604060",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "605180",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "605190",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "605050",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "605080",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "605070",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "604020",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "48",
    user: "admin",
  },
  {
    sku: "603960",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "48",
    user: "admin",
  },
  {
    sku: "603950",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "605060",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "611700",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611660",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611670",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611680",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "603945",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "606240",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "606230",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "606190",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "604030",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "606380",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "611781",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611720",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611730",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611750",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611740",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "606390",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "605171",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "606250",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "611490",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611500",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611434",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611433",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "606360",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "606400",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "604218",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "90",
    user: "admin",
  },
  {
    sku: "605220",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "606430",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "604250",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "606420",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "604240",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "606196",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "604076",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "606245",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "603957",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "606435",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "604065",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "604077",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "603944",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "603946",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "603948",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "604070",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "604130",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "604200",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "48",
    user: "admin",
  },
  {
    sku: "606232",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "603953",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "603954",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "606231",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "604211",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "602690",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "604660",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "604661",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "609341",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "600120",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "48",
    user: "admin",
  },
  {
    sku: "602440",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "602770",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "709930",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "1000",
    user: "admin",
  },
  {
    sku: "506531",
    uomFrom: "BTL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "502020",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "502040",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "501990",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "502010",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "502240",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "502030",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "604950",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "605261",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "604960",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "605000",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "616300",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "616260",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "616270",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "616290",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "616280",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "602852",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "616271",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "602820",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "602860",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "602840",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "600550",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "150",
    user: "admin",
  },
  {
    sku: "600410",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "150",
    user: "admin",
  },
  {
    sku: "610160",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "610180",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "602110",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "602090",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "601140",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "602120",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "602113",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "602140",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "602100",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "602111",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "602116",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "602119",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "610240",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "610290",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "610270",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "610250",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "610310",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "613250",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "613260",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "613272",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "613271",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "613270",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "613240",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "708410",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "708561",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "708600",
    uomFrom: "CS",
    uomTo: "CS",
    factor: "1",
    user: "admin",
  },
  {
    sku: "708580",
    uomFrom: "CS",
    uomTo: "BX",
    factor: "1",
    user: "admin",
  },
  {
    sku: "708470",
    uomFrom: "CS1",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "600800",
    uomFrom: "TUB",
    uomTo: "EA",
    factor: "300",
    user: "admin",
  },
  {
    sku: "400871",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "25",
    user: "admin",
  },
  {
    sku: "617850",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "20",
    user: "admin",
  },
  {
    sku: "400870",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "506371",
    uomFrom: "PAK",
    uomTo: "RL",
    factor: "1",
    user: "admin",
  },
  {
    sku: "400430",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "400431",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "400432",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "615060",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "615050",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "615080",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "615090",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "615040",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "615030",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "614880",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "614830",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "614450",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "615130",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "614900",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "614410",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "614320",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "614350",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "614380",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "614924",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "15",
    user: "admin",
  },
  {
    sku: "614401",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "614330",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "614440",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "614430",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "617780",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "617790",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "617671",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "617670",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "617730",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "617720",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "617710",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "617640",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "617650",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "617680",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "617700",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "617630",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "617600",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "617610",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "617690",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "617750",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "617590",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "201721",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "201561",
    uomFrom: "BTL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "301950",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "200600",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "300186",
    uomFrom: "BWL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "200840",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "200850",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "200860",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "200990",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "400710",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "400660",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "400630",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "400680",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "400600",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "400690",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "400640",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "400880",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "4",
    user: "admin",
  },
  {
    sku: "601190",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "607030",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "607040",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "600430",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "240",
    user: "admin",
  },
  {
    sku: "600570",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "240",
    user: "admin",
  },
  {
    sku: "601192",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "601193",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "601191",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "601198",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "400688",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "301627",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "301626",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "704900",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "501070",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "611629",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611634",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611633",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "613020",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "600480",
    uomFrom: "JAR",
    uomTo: "EA",
    factor: "290",
    user: "admin",
  },
  {
    sku: "600490",
    uomFrom: "TUB",
    uomTo: "EA",
    factor: "120",
    user: "admin",
  },
  {
    sku: "600470",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "120",
    user: "admin",
  },
  {
    sku: "600500",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "120",
    user: "admin",
  },
  {
    sku: "613025",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "602570",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "503310",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "613070",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "613080",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "602530",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "613030",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "202470",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "202473",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "603740",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "604340",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "604330",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "611190",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611230",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611233",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611360",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611370",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611180",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611351",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611340",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "502927",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "613095",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "602900",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "602870",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "602890",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "613130",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "613090",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "613110",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "502860",
    uomFrom: "BTL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "502970",
    uomFrom: "BTL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "503270",
    uomFrom: "BTL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "502960",
    uomFrom: "BTL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "503280",
    uomFrom: "CAN",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "503320",
    uomFrom: "BTL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "503300",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    sku: "502930",
    uomFrom: "CAN",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "503160",
    uomFrom: "BTL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "600810",
    uomFrom: "JAR",
    uomTo: "EA",
    factor: "280",
    user: "admin",
  },
  {
    sku: "600361",
    uomFrom: "BG",
    uomTo: "EA",
    factor: "360",
    user: "admin",
  },
  {
    sku: "600351",
    uomFrom: "BG",
    uomTo: "EA",
    factor: "360",
    user: "admin",
  },
  {
    sku: "600371",
    uomFrom: "BG",
    uomTo: "EA",
    factor: "360",
    user: "admin",
  },
  {
    sku: "600341",
    uomFrom: "BG",
    uomTo: "EA",
    factor: "360",
    user: "admin",
  },
  {
    sku: "600331",
    uomFrom: "BG",
    uomTo: "EA",
    factor: "360",
    user: "admin",
  },
  {
    sku: "600311",
    uomFrom: "BG",
    uomTo: "EA",
    factor: "360",
    user: "admin",
  },
  {
    sku: "600381",
    uomFrom: "BG",
    uomTo: "EA",
    factor: "360",
    user: "admin",
  },
  {
    sku: "601390",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "48",
    user: "admin",
  },
  {
    sku: "602030",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "100",
    user: "admin",
  },
  {
    sku: "605510",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "603900",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "600980",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "72",
    user: "admin",
  },
  {
    sku: "611456",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "611457",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "611458",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "604290",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "604280",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "602040",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "96",
    user: "admin",
  },
  {
    sku: "611410",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611400",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "611450",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "203000",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "619735",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "619732",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    sku: "619752",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "619727",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    sku: "619800",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "619790",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "619750",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "619770",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "619740",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    sku: "619730",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "619711",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    sku: "619760",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "619734",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "619733",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "619720",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    sku: "619710",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "6",
    user: "admin",
  },
  {
    sku: "619751",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "619755",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "604270",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "604271",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "201640",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "302520",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "302530",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "506260",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "618200",
    uomFrom: "BG",
    uomTo: "EA",
    factor: "14",
    user: "admin",
  },
  {
    sku: "202698",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "202699",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "202693",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "601160",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "601080",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "601090",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "601091",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "601130",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "601120",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "601060",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "609876",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "609880",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "15",
    user: "admin",
  },
  {
    sku: "609870",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "15",
    user: "admin",
  },
  {
    sku: "609850",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "15",
    user: "admin",
  },
  {
    sku: "609890",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "15",
    user: "admin",
  },
  {
    sku: "609881",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "15",
    user: "admin",
  },
  {
    sku: "601092",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "602500",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "602504",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "602506",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "602507",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "602511",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "602508",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "602501",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "502910",
    uomFrom: "BTL",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "618170",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "618190",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "612328",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "612540",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "612240",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "612210",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "612530",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "612710",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "612250",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "612316",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "612192",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "612332",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "612331",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "612315",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "612370",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "612314",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "612150",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "612330",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "612294",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "612510",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "612270",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "612303",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "612334",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "612306",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "612200",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "612180",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "612308",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "503403",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "503404",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "503408",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "503402",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "503409",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "503406",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "614960",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "614200",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "605520",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "605660",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "604945",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "604930",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "604946",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "604947",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "619110",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "611855",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "190",
    user: "admin",
  },
  {
    sku: "606330",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "18",
    user: "admin",
  },
  {
    sku: "601010",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "240",
    user: "admin",
  },
  {
    sku: "619135",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "60",
    user: "admin",
  },
  {
    sku: "202630",
    uomFrom: "CS",
    uomTo: "PK",
    factor: "24",
    user: "admin",
  },
  {
    sku: "202640",
    uomFrom: "CS",
    uomTo: "PK",
    factor: "24",
    user: "admin",
  },
  {
    sku: "616480",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "616490",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "616470",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "501460",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "501470",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "501430",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "501450",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "501420",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "10",
    user: "admin",
  },
  {
    sku: "402140",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "503350",
    uomFrom: "SQG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "617870",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "617910",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "32",
    user: "admin",
  },
  {
    sku: "601360",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "602011",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "48",
    user: "admin",
  },
  {
    sku: "611161",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "604511",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "602760",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "605360",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "611890",
    uomFrom: "BAG",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "605140",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "611162",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "605430",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "605460",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "604510",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "605130",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "604500",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "604570",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "604540",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "36",
    user: "admin",
  },
  {
    sku: "604970",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "611150",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "605448",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "605131",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "604560",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "602750",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "611140",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "605449",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "605447",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "611160",
    uomFrom: "BOX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "504980",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "707430",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "707550",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "500",
    user: "admin",
  },
  {
    sku: "707630",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "707470",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "503020",
    uomFrom: "SLV",
    uomTo: "SLV",
    factor: "12",
    user: "admin",
  },
  {
    sku: "201015",
    uomFrom: "CS",
    uomTo: "EA",
    factor: "8",
    user: "admin",
  },
  {
    sku: "604990",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "601950",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "48",
    user: "admin",
  },
  {
    sku: "401015",
    uomFrom: "EA",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "604948",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "601753",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "601752",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "601757",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "601751",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "601756",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "601754",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "600720",
    uomFrom: "JR",
    uomTo: "EA",
    factor: "192",
    user: "admin",
  },
  {
    sku: "604620",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "24",
    user: "admin",
  },
  {
    sku: "302531",
    uomFrom: "PAK",
    uomTo: "EA",
    factor: "1",
    user: "admin",
  },
  {
    sku: "606570",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "606632",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "15",
    user: "admin",
  },
  {
    sku: "606600",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "15",
    user: "admin",
  },
  {
    sku: "606628",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "12",
    user: "admin",
  },
  {
    sku: "606630",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "15",
    user: "admin",
  },
  {
    sku: "606625",
    uomFrom: "BX",
    uomTo: "EA",
    factor: "15",
    user: "admin",
  },
];

const seedConversion = async () => {
  await Conversion.deleteMany({});
  await Conversion.insertMany(conversionData);
};

module.exports = seedConversion;
